# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = ""
  weight = 10

[[main]]
  name = "News"
  url = "#news"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "People"
  url = "#people"
  weight = 35
  identifier = "people"

  [[main]]
    name = "Researchers"
    url = "#Researchers"
    weight = 36
    parent = "people"

  [[main]]
    name = "Principal Investigators"
    url = "#Principal Investigators"
    weight = 37
    parent = "people"

  [[main]]
    name = "Academic Staff and Senior Engineers"
    url = "#Academic Staff and Senior Engineers"
    weight = 38
    parent = "people"

  [[main]]
    name = "Associated Researchers and PIs"
    url = "#Associated Researchers and PIs"
    weight = 39
    parent = "people"

  [[main]]
    name = "Project Management"
    url = "#Project Management"
    weight = 40
    parent = "people"

  [[main]]
    name = "Alumni"
    url = "#Alumni"
    weight = 41
    parent = "people"

[[main]]
  name = "Results"
  url  = "#results"
  weight = 45
  identifier = "results"

  [[main]]
    name = "Software"
    url = "#software"
    weight = 46
    parent = "results"

  [[main]]
    name = "Data"
    url = "#data"
    weight = 47
    parent = "results"

  [[main]]
    name = "Talks"
    url = "#talks"
    weight = 50
    parent = "results"

  [[main]]
    name = "Publications"
    url = "#publications"
    weight = 55
    parent = "results"
  [[main]]
    name = "Media"
    url = "#media"
    weight = 56
    parent = "media"

[[main]]
  name = "About"
  url = "#about"
  weight = 60
  identifier = "about"

  [[main]]
    name = "Summary"
    url = "/summary"
    weight = 61
    parent = "about"

  [[main]]
    name = "Consortium"
    url = "#consortium"
    weight = 62
    parent = "about"

  [[main]]
    name = "Contact"
    url = "#contact"
    weight = 63
    parent = "about"

[[main]]
  name = "Wiki(Login)"
  url = "http://www.awesco.eu/wiki"
  weight = 70

[[main]]
  name = "<i class='ai ai-researchgate' style='font-size: 1.1rem'></i>"
  url = "https://www.researchgate.net/project/AWESCO-Airborne-Wind-Energy-System-Modelling-Control-and-Optimisation"
  weight = 90

[[main]]
  name = "<i class='fab fa-linkedin-in'></i>"
  url = "https://www.linkedin.com/groups/8277365/"
  weight = 95

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
